# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byoc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='byoc.proto',
  package='byoc',
  syntax='proto3',
  serialized_pb=_b('\n\nbyoc.proto\x12\x04\x62yoc\" \n\x0bTaskRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"B\n\x0cTaskResponse\x12\x10\n\x08has_task\x18\x01 \x01(\x08\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"\\\n\rResultRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x16\n\x0estatus_message\x18\x04 \x01(\t\"&\n\x0eResultResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32}\n\x0c\x43ontrolPlane\x12\x32\n\tFetchTask\x12\x11.byoc.TaskRequest\x1a\x12.byoc.TaskResponse\x12\x39\n\x0cSubmitResult\x12\x13.byoc.ResultRequest\x1a\x14.byoc.ResultResponseb\x06proto3')
)




_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='byoc.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='byoc.TaskRequest.worker_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=52,
)


_TASKRESPONSE = _descriptor.Descriptor(
  name='TaskResponse',
  full_name='byoc.TaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_task', full_name='byoc.TaskResponse.has_task', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='byoc.TaskResponse.task_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='byoc.TaskResponse.command', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=120,
)


_RESULTREQUEST = _descriptor.Descriptor(
  name='ResultRequest',
  full_name='byoc.ResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='byoc.ResultRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='byoc.ResultRequest.worker_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='byoc.ResultRequest.success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='byoc.ResultRequest.status_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=214,
)


_RESULTRESPONSE = _descriptor.Descriptor(
  name='ResultResponse',
  full_name='byoc.ResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acknowledged', full_name='byoc.ResultResponse.acknowledged', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=254,
)

DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE
DESCRIPTOR.message_types_by_name['ResultRequest'] = _RESULTREQUEST
DESCRIPTOR.message_types_by_name['ResultResponse'] = _RESULTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _TASKREQUEST,
  __module__ = 'byoc_pb2'
  # @@protoc_insertion_point(class_scope:byoc.TaskRequest)
  ))
_sym_db.RegisterMessage(TaskRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _TASKRESPONSE,
  __module__ = 'byoc_pb2'
  # @@protoc_insertion_point(class_scope:byoc.TaskResponse)
  ))
_sym_db.RegisterMessage(TaskResponse)

ResultRequest = _reflection.GeneratedProtocolMessageType('ResultRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESULTREQUEST,
  __module__ = 'byoc_pb2'
  # @@protoc_insertion_point(class_scope:byoc.ResultRequest)
  ))
_sym_db.RegisterMessage(ResultRequest)

ResultResponse = _reflection.GeneratedProtocolMessageType('ResultResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESULTRESPONSE,
  __module__ = 'byoc_pb2'
  # @@protoc_insertion_point(class_scope:byoc.ResultResponse)
  ))
_sym_db.RegisterMessage(ResultResponse)



_CONTROLPLANE = _descriptor.ServiceDescriptor(
  name='ControlPlane',
  full_name='byoc.ControlPlane',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=256,
  serialized_end=381,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchTask',
    full_name='byoc.ControlPlane.FetchTask',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitResult',
    full_name='byoc.ControlPlane.SubmitResult',
    index=1,
    containing_service=None,
    input_type=_RESULTREQUEST,
    output_type=_RESULTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLPLANE)

DESCRIPTOR.services_by_name['ControlPlane'] = _CONTROLPLANE

# @@protoc_insertion_point(module_scope)
