# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import byoc_pb2 as byoc__pb2


class ControlPlaneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FetchTask = channel.unary_unary(
        '/byoc.ControlPlane/FetchTask',
        request_serializer=byoc__pb2.TaskRequest.SerializeToString,
        response_deserializer=byoc__pb2.TaskResponse.FromString,
        )
    self.SubmitResult = channel.unary_unary(
        '/byoc.ControlPlane/SubmitResult',
        request_serializer=byoc__pb2.ResultRequest.SerializeToString,
        response_deserializer=byoc__pb2.ResultResponse.FromString,
        )


class ControlPlaneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FetchTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FetchTask': grpc.unary_unary_rpc_method_handler(
          servicer.FetchTask,
          request_deserializer=byoc__pb2.TaskRequest.FromString,
          response_serializer=byoc__pb2.TaskResponse.SerializeToString,
      ),
      'SubmitResult': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitResult,
          request_deserializer=byoc__pb2.ResultRequest.FromString,
          response_serializer=byoc__pb2.ResultResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'byoc.ControlPlane', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
